### PR TITLE
Add showdown option for displaying tables in-line.

### PR DESCRIPTION
**Pull request by FlipperPA**

### CODE REVIEW

**Comment by FlipperPA** [comment]
@MiltonLn Can you have a look at this? This should turn on tables in ShowdownJS as well. I'm hoping they're in the same format. I'll test later this week, but figured you'd want to see. I also changed the imports for bleach to only import what is necessary.

**Comment by MiltonLn** [comment]
Ok, i'm taking a look, thanks!

**Comment by MiltonLn** [comment]
Ok, i have tested your showdown enhancement for tables.

It works, on the real-time previewer it shows the table html structure but not styled:

image
i like to have a discussion about it on issue #3 .

The tables are also not styled on the entry page, i will give a solution i did on my pull request on puput
about the bleach import that's great :D

**Comment by MiltonLn** [comment]
Any response here?

**Comment by FlipperPA** [comment]
I'm closing this PR, as I've pulled in the changes for SimpleMDE. Thanks a bundle, Milton!

**Pull request closed without merging**
